using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MySql.Data.MySqlClient;

namespace SalonDeBelleza
{
    public partial class Historial : Form
    {
        Clases.Conexion conexion = new Clases.Conexion();
        public Historial()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void gvReservacion_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }
        private void ListarHistorial(MySqlConnection con, int idCliente)
        {
            dataGridView1.DataSource = Clases.Historial.Buscar(con, idCliente);
        }
        private void Historial_Load(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                if (conexion.abrirConexion() == true)
                {
                    ListarHistorial(conexion.conexion, Convert.ToInt32(lookUpEdit1.Text));
                }
            }
            catch (Exception ex)
            {

                MessageBox.Show(ex.ToString());
            }
            finally { conexion.cerrarConexion(); }
            
        }

        private void btnAceptar_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}
