using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using MySql.Data.MySqlClient;

namespace SalonDeBelleza
{
    public partial class Reservaciones : DevExpress.XtraEditors.XtraForm
    {
        Clases.Conexion conexion = new Clases.Conexion();
        public Reservaciones()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource4.Fill();
        }

        private void Reservaciones_Load(object sender, EventArgs e)
        {

        }

        private void btnGuardar_Click(object sender, EventArgs e)
        {
            try
            {
                if (conexion.abrirConexion() == true)
                {
                    Clases.Reservaciones pReservaciones = new Clases.Reservaciones();
                    pReservaciones.fechaAtencion = dateFechaAtencion.Text;
                    pReservaciones.hora = txtAtentidoPor.Text;
                    pReservaciones.idCliente = Convert.ToInt32(lookUpEdit1.Text);
                    pReservaciones.fechaReservacion = dateFechaReservacion.Text;

                    
                    int resultado;
                    resultado = Clases.Reservaciones.agregarReservacion(conexion.conexion, pReservaciones);

                    if (resultado > 0)
                    {
                        txtAtentidoPor.Clear();
                        dateFechaReservacion.Text = "";
                        dateFechaAtencion.Text = "";
                        lookUpEdit1.Text = "";
                        sqlDataSource4.Fill();
                    }
                    
                }
                else
                {
                    MessageBox.Show("No se Conecto!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally { conexion.cerrarConexion(); }
        }

        private void btnRegresar_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}