using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SalonDeBelleza
{
    public partial class Servicios : Form
    {
        Clases.Conexion conexion = new Clases.Conexion();
        public Servicios()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btnGuardar_Click(object sender, EventArgs e)
        {
            try
            {
                if (conexion.abrirConexion() == true)
                {
                    Clases.Servicio pServicio = new Clases.Servicio();
                    pServicio.IdServicio = Convert.ToInt32(txtServicio.Text);
                    pServicio.NombreServicio  = txtNombreServicio.Text;
                    pServicio.Horas = txtHoras.Text;
                    pServicio.Empleado = Convert.ToInt32(lookUpEdit1.Text);
                    pServicio.Genero = txtGenero.Text;

                    int resultado;
                    resultado = Clases.Servicio.AgregarServicio(conexion.conexion, pServicio);
                    if (resultado > 0)
                    {
                        txtGenero.Text="";
                        txtHoras.Clear();
                        txtNombreServicio.Clear();
                        txtServicio.Clear();
                        lookUpEdit1.Text = "";
                        sqlDataSource1.Fill();
                    }
                    conexion.cerrarConexion();
                }
                else
                {
                    MessageBox.Show("No se Conecto!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnActualizar_Click(object sender, EventArgs e)
        {
            try
            {
                if (conexion.abrirConexion() == true)
                {
                    Clases.Servicio pServicio = new Clases.Servicio();
                    pServicio.IdServicio = Convert.ToInt32(txtServicio.Text);
                    pServicio.NombreServicio = txtNombreServicio.Text;
                    pServicio.Horas = txtHoras.Text;
                    pServicio.Empleado = Convert.ToInt32(lookUpEdit1.Text);
                    pServicio.Genero = txtGenero.Text;

                    int resultado;
                    resultado = Clases.Servicio.ActualizarServicio(conexion.conexion, pServicio);
                    if (resultado > 0)
                    {
                        txtHoras.Clear();
                        txtNombreServicio.Clear();
                        txtServicio.Clear();
                        lookUpEdit1.Text = "";
                        sqlDataSource1.Fill();
                    }
                    conexion.cerrarConexion();
                }
                else
                {
                    MessageBox.Show("No se Conecto!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnEliminar_Click(object sender, EventArgs e)
        {
            try
            {
                if (conexion.abrirConexion() == true)
                {
                    Clases.Servicio pServicio = new Clases.Servicio();
                    pServicio.IdServicio = Convert.ToInt32(txtServicio.Text);

                    int resultado;
                    resultado = Clases.Servicio.EliminarServicio(conexion.conexion, pServicio);
                    if (resultado > 0)
                    {
                        txtHoras.Clear();
                        txtNombreServicio.Clear();
                        txtServicio.Clear();
                        lookUpEdit1.Text = "";
                        sqlDataSource1.Fill();
                    }
                    conexion.cerrarConexion();
                }
                else
                {
                    MessageBox.Show("No se Conecto!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnCerrar_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void Servicios_Load(object sender, EventArgs e)
        {

        }

        private void txtNombreServicio_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (Char.IsDigit(e.KeyChar))
            {
                e.Handled = true;
            }
            else if (Char.IsControl(e.KeyChar))
            {
                e.Handled = false;
            }
            else
            {
                e.Handled = false;
            }
        }
    }
}
